//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtcAddress.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BtcAddress.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  bytes..
        /// </summary>
        internal static string Pbkdf2_Read__bytes_ {
            get {
                return ResourceManager.GetString("Pbkdf2_Read__bytes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only return .
        /// </summary>
        internal static string Pbkdf2_Read_Can_only_return_ {
            get {
                return ResourceManager.GetString("Pbkdf2_Read_Can_only_return_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeking before the stream start..
        /// </summary>
        internal static string Pbkdf2_Seek_Seeking_before_the_stream_start_ {
            get {
                return ResourceManager.GetString("Pbkdf2_Seek_Seeking_before_the_stream_start_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown seek type..
        /// </summary>
        internal static string Pbkdf2_Seek_Unknown_seek_type_ {
            get {
                return ResourceManager.GetString("Pbkdf2_Seek_Unknown_seek_type_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost must be a positive power of 2..
        /// </summary>
        internal static string SCrypt_MFcrypt_Cost_must_be_a_positive_power_of_2_ {
            get {
                return ResourceManager.GetString("SCrypt_MFcrypt_Cost_must_be_a_positive_power_of_2_", resourceCulture);
            }
        }
    }
}
