//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtcAddress.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BtcAddress.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort generation.
        /// </summary>
        internal static string AddressGen_AddressGen_FormClosing_Abort_generation {
            get {
                return ResourceManager.GetString("AddressGen_AddressGen_FormClosing_Abort_generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and abandon generation in progress?.
        /// </summary>
        internal static string AddressGen_AddressGen_FormClosing_Cancel_and_abandon_generation_in_progress_ {
            get {
                return ResourceManager.GetString("AddressGen_AddressGen_FormClosing_Cancel_and_abandon_generation_in_progress_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A deterministic seed is required.  If you do not intend to create a deterministic wallet or know what one is used for, it is recommended you choose one of the other options.  An inappropriate seed can result in the unexpected theft of funds..
        /// </summary>
        internal static string AddressGen_btnGenerateAddresses_Click_A_deterministic_seed_is_required___If_you_do_not_intend_to_create_a_deterministic_wallet_or_know_what_one_is_used_for__it_is_recommended_you_choose_one_of_the_other_options___An_inappropriate_seed_can_result_in_the_unexpected_theft_of_funds_ {
            get {
                return ResourceManager.GetString(@"AddressGen_btnGenerateAddresses_Click_A_deterministic_seed_is_required___If_you_do_not_intend_to_create_a_deterministic_wallet_or_know_what_one_is_used_for__it_is_recommended_you_choose_one_of_the_other_options___An_inappropriate_seed_can_result_in_the_unexpected_theft_of_funds_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An encryption passphrase is required. Choose a different option if you don&apos;t want encrypted keys..
        /// </summary>
        internal static string AddressGen_btnGenerateAddresses_Click_An_encryption_passphrase_is_required__Choose_a_different_option_if_you_don_t_want_encrypted_keys_ {
            get {
                return ResourceManager.GetString("AddressGen_btnGenerateAddresses_Click_An_encryption_passphrase_is_required__Choos" +
                        "e_a_different_option_if_you_don_t_want_encrypted_keys_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AddressGen_btnGenerateAddresses_Click_Cancel {
            get {
                return ResourceManager.GetString("AddressGen_btnGenerateAddresses_Click_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No intermediate codes found.
        /// </summary>
        internal static string AddressGen_btnGenerateAddresses_Click_No_intermediate_codes_found {
            get {
                return ResourceManager.GetString("AddressGen_btnGenerateAddresses_Click_No_intermediate_codes_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid intermediate codes were found on the clipboard.  Intermediate codes are typically sent to you from someone else desiring paper wallets, or from your mobile phone.  Copy the received intermediate codes to the clipboard, and try again.  Address Generator automatically detects valid intermediate codes and ignores everything else on the clipboard.
        /// </summary>
        internal static string AddressGen_btnGenerateAddresses_Click_No_valid_intermediate_codes_were_found_on_the_clipboard___Intermediate_codes_are_typically_sent_to_you_from_someone_else_desiring_paper_wallets__or_from_your_mobile_phone___Copy_the_received_intermediate_codes_to_the_clipboard__and_try_again___Address_Generator_automatically_detects_valid_intermediate_codes_and_ignores_everything_else_on_the_clipboard {
            get {
                return ResourceManager.GetString(@"AddressGen_btnGenerateAddresses_Click_No_valid_intermediate_codes_were_found_on_the_clipboard___Intermediate_codes_are_typically_sent_to_you_from_someone_else_desiring_paper_wallets__or_from_your_mobile_phone___Copy_the_received_intermediate_codes_to_the_clipboard__and_try_again___Address_Generator_automatically_detects_valid_intermediate_codes_and_ignores_everything_else_on_the_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase missing.
        /// </summary>
        internal static string AddressGen_btnGenerateAddresses_Click_Passphrase_missing {
            get {
                return ResourceManager.GetString("AddressGen_btnGenerateAddresses_Click_Passphrase_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed missing.
        /// </summary>
        internal static string AddressGen_btnGenerateAddresses_Click_Seed_missing {
            get {
                return ResourceManager.GetString("AddressGen_btnGenerateAddresses_Click_Seed_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        internal static string AddressGen_btnGenerateAddresses_Click_Stopping___ {
            get {
                return ResourceManager.GetString("AddressGen_btnGenerateAddresses_Click_Stopping___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  intermediate codes found on clipboard..
        /// </summary>
        internal static string AddressGen_rdoWalletType_CheckedChanged__intermediate_codes_found_on_clipboard_ {
            get {
                return ResourceManager.GetString("AddressGen_rdoWalletType_CheckedChanged__intermediate_codes_found_on_clipboard_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy one or more intermediate codes to the clipboard..
        /// </summary>
        internal static string AddressGen_rdoWalletType_CheckedChanged_Copy_one_or_more_intermediate_codes_to_the_clipboard_ {
            get {
                return ResourceManager.GetString("AddressGen_rdoWalletType_CheckedChanged_Copy_one_or_more_intermediate_codes_to_th" +
                        "e_clipboard_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption passphrase or Intermediate Code.
        /// </summary>
        internal static string AddressGen_rdoWalletType_CheckedChanged_Encryption_passphrase_or_Intermediate_Code {
            get {
                return ResourceManager.GetString("AddressGen_rdoWalletType_CheckedChanged_Encryption_passphrase_or_Intermediate_Cod" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed for deterministic generation.
        /// </summary>
        internal static string AddressGen_rdoWalletType_CheckedChanged_Seed_for_deterministic_generation {
            get {
                return ResourceManager.GetString("AddressGen_rdoWalletType_CheckedChanged_Seed_for_deterministic_generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  generated keys?.
        /// </summary>
        internal static string AddressGen_timer1_Tick__generated_keys_ {
            get {
                return ResourceManager.GetString("AddressGen_timer1_Tick__generated_keys_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel generation.
        /// </summary>
        internal static string AddressGen_timer1_Tick_Cancel_generation {
            get {
                return ResourceManager.GetString("AddressGen_timer1_Tick_Cancel_generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Addresses.
        /// </summary>
        internal static string AddressGen_timer1_Tick_Generate_Addresses {
            get {
                return ResourceManager.GetString("AddressGen_timer1_Tick_Generate_Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashing the passphrase....
        /// </summary>
        internal static string AddressGen_timer1_Tick_Hashing_the_passphrase___ {
            get {
                return ResourceManager.GetString("AddressGen_timer1_Tick_Hashing_the_passphrase___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the .
        /// </summary>
        internal static string AddressGen_timer1_Tick_Keep_the_ {
            get {
                return ResourceManager.GetString("AddressGen_timer1_Tick_Keep_the_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys generated: .
        /// </summary>
        internal static string AddressGen_timer1_Tick_Keys_generated__ {
            get {
                return ResourceManager.GetString("AddressGen_timer1_Tick_Keys_generated__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Multiple Addresses.
        /// </summary>
        internal static string AddSingleAddress_btnGoMulti_Click_Add_Multiple_Addresses {
            get {
                return ResourceManager.GetString("AddSingleAddress_btnGoMulti_Click_Add_Multiple_Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter or paste text. Addresses and keys will be picked out..
        /// </summary>
        internal static string AddSingleAddress_btnGoMulti_Click_Enter_or_paste_text__Addresses_and_keys_will_be_picked_out_ {
            get {
                return ResourceManager.GetString("AddSingleAddress_btnGoMulti_Click_Enter_or_paste_text__Addresses_and_keys_will_be" +
                        "_picked_out_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a key first..
        /// </summary>
        internal static string AddSingleAddress_button1_Click_Enter_a_key_first_ {
            get {
                return ResourceManager.GetString("AddSingleAddress_button1_Click_Enter_a_key_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized or invalid string.
        /// </summary>
        internal static string AddSingleAddress_button1_Click_Unrecognized_or_invalid_string {
            get {
                return ResourceManager.GetString("AddSingleAddress_button1_Click_Unrecognized_or_invalid_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Base58 length: .
        /// </summary>
        internal static string Base58Calc_UpdateByteCounts___Base58_length__ {
            get {
                return ResourceManager.GetString("Base58Calc_UpdateByteCounts___Base58_length__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes: .
        /// </summary>
        internal static string Base58Calc_UpdateByteCounts_Bytes__ {
            get {
                return ResourceManager.GetString("Base58Calc_UpdateByteCounts_Bytes__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .  Perhaps you entered the wrong thing?  Confirmation codes .
        /// </summary>
        internal static string Bip38ConfValidator_btnConfirm_Click____Perhaps_you_entered_the_wrong_thing___Confirmation_codes_ {
            get {
                return ResourceManager.GetString("Bip38ConfValidator_btnConfirm_Click____Perhaps_you_entered_the_wrong_thing___Conf" +
                        "irmation_codes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation code is required..
        /// </summary>
        internal static string Bip38ConfValidator_btnConfirm_Click_Confirmation_code_is_required_ {
            get {
                return ResourceManager.GetString("Bip38ConfValidator_btnConfirm_Click_Confirmation_code_is_required_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation code required.
        /// </summary>
        internal static string Bip38ConfValidator_btnConfirm_Click_Confirmation_code_required {
            get {
                return ResourceManager.GetString("Bip38ConfValidator_btnConfirm_Click_Confirmation_code_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid confirmation code.
        /// </summary>
        internal static string Bip38ConfValidator_btnConfirm_Click_Invalid_confirmation_code {
            get {
                return ResourceManager.GetString("Bip38ConfValidator_btnConfirm_Click_Invalid_confirmation_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid passphrase.
        /// </summary>
        internal static string Bip38ConfValidator_btnConfirm_Click_Invalid_passphrase {
            get {
                return ResourceManager.GetString("Bip38ConfValidator_btnConfirm_Click_Invalid_passphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase is required..
        /// </summary>
        internal static string Bip38ConfValidator_btnConfirm_Click_Passphrase_is_required_ {
            get {
                return ResourceManager.GetString("Bip38ConfValidator_btnConfirm_Click_Passphrase_is_required_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase required.
        /// </summary>
        internal static string Bip38ConfValidator_btnConfirm_Click_Passphrase_required {
            get {
                return ResourceManager.GetString("Bip38ConfValidator_btnConfirm_Click_Passphrase_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start with &quot;cfrm&quot;..
        /// </summary>
        internal static string Bip38ConfValidator_btnConfirm_Click_start_with__cfrm__ {
            get {
                return ResourceManager.GetString("Bip38ConfValidator_btnConfirm_Click_start_with__cfrm__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is actually a private key.
        /// </summary>
        internal static string Bip38ConfValidator_btnConfirm_Click_This_is_actually_a_private_key {
            get {
                return ResourceManager.GetString("Bip38ConfValidator_btnConfirm_Click_This_is_actually_a_private_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid confirmation code..
        /// </summary>
        internal static string Bip38ConfValidator_btnConfirm_Click_This_is_not_a_valid_confirmation_code_ {
            get {
                return ResourceManager.GetString("Bip38ConfValidator_btnConfirm_Click_This_is_not_a_valid_confirmation_code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid confirmation code.  Instead, it looks like .
        /// </summary>
        internal static string Bip38ConfValidator_btnConfirm_Click_This_is_not_a_valid_confirmation_code___Instead__it_looks_like_ {
            get {
                return ResourceManager.GetString("Bip38ConfValidator_btnConfirm_Click_This_is_not_a_valid_confirmation_code___Inste" +
                        "ad__it_looks_like_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid confirmation code.  It has the right prefix, but doesn&apos;t contain valid confirmation data.  Possible typo or incomplete?.
        /// </summary>
        internal static string Bip38ConfValidator_btnConfirm_Click_This_is_not_a_valid_confirmation_code___It_has_the_right_prefix__but_doesn_t_contain_valid_confirmation_data___Possible_typo_or_incomplete_ {
            get {
                return ResourceManager.GetString("Bip38ConfValidator_btnConfirm_Click_This_is_not_a_valid_confirmation_code___It_ha" +
                        "s_the_right_prefix__but_doesn_t_contain_valid_confirmation_data___Possible_typo_" +
                        "or_incomplete_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid confirmation code.  It looks like an encrypted private key.  Decryption was attempted but the passphrase couldn&apos;t decrypt it.
        /// </summary>
        internal static string Bip38ConfValidator_btnConfirm_Click_This_is_not_a_valid_confirmation_code___It_looks_like_an_encrypted_private_key___Decryption_was_attempted_but_the_passphrase_couldn_t_decrypt_it {
            get {
                return ResourceManager.GetString("Bip38ConfValidator_btnConfirm_Click_This_is_not_a_valid_confirmation_code___It_lo" +
                        "oks_like_an_encrypted_private_key___Decryption_was_attempted_but_the_passphrase_" +
                        "couldn_t_decrypt_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This passphrase is wrong or does not belong to this confirmation code..
        /// </summary>
        internal static string Bip38ConfValidator_btnConfirm_Click_This_passphrase_is_wrong_or_does_not_belong_to_this_confirmation_code_ {
            get {
                return ResourceManager.GetString("Bip38ConfValidator_btnConfirm_Click_This_passphrase_is_wrong_or_does_not_belong_t" +
                        "o_this_confirmation_code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you provided contains a private key, not just a confirmation. Confirmation is successful, and with this correct passphrase, you are also able to spend the funds from the address..
        /// </summary>
        internal static string Bip38ConfValidator_btnConfirm_Click_What_you_provided_contains_a_private_key__not_just_a_confirmation__Confirmation_is_successful__and_with_this_correct_passphrase__you_are_also_able_to_spend_the_funds_from_the_address_ {
            get {
                return ResourceManager.GetString("Bip38ConfValidator_btnConfirm_Click_What_you_provided_contains_a_private_key__not" +
                        "_just_a_confirmation__Confirmation_is_successful__and_with_this_correct_passphra" +
                        "se__you_are_also_able_to_spend_the_funds_from_the_address_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both of the key inputs have the same public key hash.  You can continue, but the results are probably going to be wrong.  You might have provided the wrong information, such as two parts from the same side of the transaction, instead of one part from each side.  Continue anyway?.
        /// </summary>
        internal static string KeyCombiner_btnCombine_Click_Both_of_the_key_inputs_have_the_same_public_key_hash___You_can_continue__but_the_results_are_probably_going_to_be_wrong___You_might_have_provided_the_wrong_information__such_as_two_parts_from_the_same_side_of_the_transaction__instead_of_one_part_from_each_side___Continue_anyway_ {
            get {
                return ResourceManager.GetString(@"KeyCombiner_btnCombine_Click_Both_of_the_key_inputs_have_the_same_public_key_hash___You_can_continue__but_the_results_are_probably_going_to_be_wrong___You_might_have_provided_the_wrong_information__such_as_two_parts_from_the_same_side_of_the_transaction__instead_of_one_part_from_each_side___Continue_anyway_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t combine.
        /// </summary>
        internal static string KeyCombiner_btnCombine_Click_Can_t_combine {
            get {
                return ResourceManager.GetString("KeyCombiner_btnCombine_Click_Can_t_combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t combine a compressed key with an uncompressed key..
        /// </summary>
        internal static string KeyCombiner_btnCombine_Click_Can_t_combine_a_compressed_key_with_an_uncompressed_key_ {
            get {
                return ResourceManager.GetString("KeyCombiner_btnCombine_Click_Can_t_combine_a_compressed_key_with_an_uncompressed_" +
                        "key_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t multiply two public keys.  At least one of the keys must be a private key..
        /// </summary>
        internal static string KeyCombiner_btnCombine_Click_Can_t_multiply_two_public_keys___At_least_one_of_the_keys_must_be_a_private_key_ {
            get {
                return ResourceManager.GetString("KeyCombiner_btnCombine_Click_Can_t_multiply_two_public_keys___At_least_one_of_the" +
                        "_keys_must_be_a_private_key_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input key #1 is not a valid Public Key or Private Key Hex.
        /// </summary>
        internal static string KeyCombiner_btnCombine_Click_Input_key__1_is_not_a_valid_Public_Key_or_Private_Key_Hex {
            get {
                return ResourceManager.GetString("KeyCombiner_btnCombine_Click_Input_key__1_is_not_a_valid_Public_Key_or_Private_Ke" +
                        "y_Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input key #2 is not a valid Public Key or Private Key Hex.
        /// </summary>
        internal static string KeyCombiner_btnCombine_Click_Input_key__2_is_not_a_valid_Public_Key_or_Private_Key_Hex {
            get {
                return ResourceManager.GetString("KeyCombiner_btnCombine_Click_Input_key__2_is_not_a_valid_Public_Key_or_Private_Ke" +
                        "y_Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only available when combining two private keys.
        /// </summary>
        internal static string KeyCombiner_btnCombine_Click_Only_available_when_combining_two_private_keys {
            get {
                return ResourceManager.GetString("KeyCombiner_btnCombine_Click_Only_available_when_combining_two_private_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EC Addition should not be used for two-factor storage.  Use multiplication instead. Addition is safe when employing a vanity pool to generate vanity addresses, and is required for vanity address generators to achieve GPU-accelerated performance.  For some other uses, addition is unsafe due to its reversibility, so always use multiplication instead wherever possible..
        /// </summary>
        internal static string KeyCombiner_linkLabel1_LinkClicked_EC_Addition_should_not_be_used_for_two_factor_storage___Use_multiplication_instead__Addition_is_safe_when_employing_a_vanity_pool_to_generate_vanity_addresses__and_is_required_for_vanity_address_generators_to_achieve_GPU_accelerated_performance___For_some_other_uses__addition_is_unsafe_due_to_its_reversibility__so_always_use_multiplication_instead_wherever_possible_ {
            get {
                return ResourceManager.GetString(@"KeyCombiner_linkLabel1_LinkClicked_EC_Addition_should_not_be_used_for_two_factor_storage___Use_multiplication_instead__Addition_is_safe_when_employing_a_vanity_pool_to_generate_vanity_addresses__and_is_required_for_vanity_address_generators_to_achieve_GPU_accelerated_performance___For_some_other_uses__addition_is_unsafe_due_to_its_reversibility__so_always_use_multiplication_instead_wherever_possible_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough valid parts were present to decode an address..
        /// </summary>
        internal static string MofNcalc_btnDecode_Click_Not_enough_valid_parts_were_present_to_decode_an_address_ {
            get {
                return ResourceManager.GetString("MofNcalc_btnDecode_Click_Not_enough_valid_parts_were_present_to_decode_an_address" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of parts needed exceeds number of parts to generate..
        /// </summary>
        internal static string MofNcalc_btnGenerate_Clicxk_Number_of_parts_needed_exceeds_number_of_parts_to_generate_ {
            get {
                return ResourceManager.GetString("MofNcalc_btnGenerate_Clicxk_Number_of_parts_needed_exceeds_number_of_parts_to_gen" +
                        "erate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid private key..
        /// </summary>
        internal static string MofNcalc_btnGenerateSpecific_Click_Not_a_valid_private_key_ {
            get {
                return ResourceManager.GetString("MofNcalc_btnGenerateSpecific_Click_Not_a_valid_private_key_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is experimental, a proof of concept, and the key format will probably be revised heavily before this ever makes it into production.  Don&apos;t rely on it to secure large numbers of Bitcoins.  If you use it, make sure you keep a copy of this version of the utility in case the m-of-n format is changed before being accepted as any kind of standard..
        /// </summary>
        internal static string MofNcalc_MofNcalc_Load_This_feature_is_experimental__a_proof_of_concept__and_the_key_format_will_probably_be_revised_heavily_before_this_ever_makes_it_into_production___Don_t_rely_on_it_to_secure_large_numbers_of_Bitcoins___If_you_use_it__make_sure_you_keep_a_copy_of_this_version_of_the_utility_in_case_the_m_of_n_format_is_changed_before_being_accepted_as_any_kind_of_standard_ {
            get {
                return ResourceManager.GetString(@"MofNcalc_MofNcalc_Load_This_feature_is_experimental__a_proof_of_concept__and_the_key_format_will_probably_be_revised_heavily_before_this_ever_makes_it_into_production___Don_t_rely_on_it_to_secure_large_numbers_of_Bitcoins___If_you_use_it__make_sure_you_keep_a_copy_of_this_version_of_the_utility_in_case_the_m_of_n_format_is_changed_before_being_accepted_as_any_kind_of_standard_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  bytes..
        /// </summary>
        internal static string Pbkdf2_Read__bytes_ {
            get {
                return ResourceManager.GetString("Pbkdf2_Read__bytes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only return .
        /// </summary>
        internal static string Pbkdf2_Read_Can_only_return_ {
            get {
                return ResourceManager.GetString("Pbkdf2_Read_Can_only_return_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeking before the stream start..
        /// </summary>
        internal static string Pbkdf2_Seek_Seeking_before_the_stream_start_ {
            get {
                return ResourceManager.GetString("Pbkdf2_Seek_Seeking_before_the_stream_start_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown seek type..
        /// </summary>
        internal static string Pbkdf2_Seek_Unknown_seek_type_ {
            get {
                return ResourceManager.GetString("Pbkdf2_Seek_Unknown_seek_type_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost must be a positive power of 2..
        /// </summary>
        internal static string SCrypt_MFcrypt_Cost_must_be_a_positive_power_of_2_ {
            get {
                return ResourceManager.GetString("SCrypt_MFcrypt_Cost_must_be_a_positive_power_of_2_", resourceCulture);
            }
        }
    }
}
